project: 
  type: website
  output-dir: docs
  resources:
    - ready-exercise/

website:
  title: "Rebecca Basta Data Analysis Portfolio"
  navbar:
    left:
      - text: "About Me"
        file: aboutme.qmd
      - text: "Projects"
        menu:
          - text: "Starter Analysis Exercise"
            file: starter-analysis-exercise/starter-analysis-exercise.qmd
          - text: "READy Exercise"
            href: ready-exercise/
          - text: "Data Exercise"
            file: data-exercise/data-exercise.qmd
          - text: "Data Analysis Exercise"
            file: cdcdata-exercise/cdcdata-exercise.qmd
          - text: "Presentation Exercise"
            file: presentation-exercise/presentation-exercise.qmd
    right:
      - icon: github 
        href: https://github.com/rebeccabasta/rebeccabasta-portfolio       
format:
  html:
      self-contained: true
      theme: minty
      highlight: zenburn
      css: styles.css
      toc: FALSE
